version: '3.4'

services:
  fiap.techchalenge.investnethub.db:
    container_name: investnethubdb
    hostname: investnethubdb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: C0D3fl1x.@

networks:
  default: 
    name: service_investnethub

